apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea-kube-deply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea-kube
  template:
    metadata:
      labels:
        app: servicea-kube
    spec:
      containers:
        - name: servicea-node
          image: manasadvr0628/servicea-kube:v3

